const sharedGlobals = Object.fromEntries([
  "AbortController",
  "Buffer",
  "ClipboardItem",
  "Blob",
  "CSS",
  "atob",
  "CustomEvent",
  "DOMException",
  "Document",
  "Event",
  "FileReader",
  "HTMLCanvasElement",
  "HTMLElement",
  "HTMLInputElement",
  "HTMLTextAreaElement",
  "Image",
  "KeyboardEvent",
  "MouseEvent",
  "OffscreenCanvas",
  "PointerEvent",
  "URL",
  "URLSearchParams",
  "WebSocket",
  "window",
  "browser",
  "chrome",
  "clearInterval",
  "clearTimeout",
  "console",
  "crypto",
  "createImageBitmap",
  "document",
  "fetch",
  "getComputedStyle",
  "globalThis",
  "indexedDB",
  "location",
  "navigator",
  "performance",
  "process",
  "require",
  "requestAnimationFrame",
  "setInterval",
  "setTimeout",
  "structuredClone",
].map((name) => [name, "readonly"]));

export default [
  {
    ignores: ["dist/**", "node_modules/**"],
  },
  {
    files: ["extension/**/*.js", "scripts/**/*.cjs", "scripts/**/*.mjs", "tests/**/*.js", "tests/**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: sharedGlobals,
    },
    rules: {
      "no-undef": "error",
    },
  },
];
